name: Descargar Estadísticas ENARGAS

# Se puede ejecutar manualmente desde la pestaña "Actions" de GitHub
on: 
  workflow_dispatch:
  # Si quieres que se ejecute automáticamente, descomenta las siguientes líneas
  # schedule:
  #   - cron: '0 10 * * 1' # Todos los lunes a las 10:00 AM UTC

jobs:
  descargar-excel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar Script de Descarga
        run: python script_enargas.py

      - name: Subir archivos Excel descargados como Artefactos
        uses: actions/upload-artifact@v4
        with:
          name: Archivos-GNC-2026
          path: descargas_gnc/*.xls
          retention-days: 7
