name: Descargar Estadísticas ENARGAS

on: 
  workflow_dispatch:

jobs:
  descargar-excel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # NUEVO PASO: Instalar el monitor virtual en el servidor de GitHub
      - name: Instalar Xvfb (Monitor Virtual)
        run: sudo apt-get update && sudo apt-get install -y xvfb

      # NUEVO COMANDO: Ejecutar Python a través de la pantalla virtual
      - name: Ejecutar Script de Descarga
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python script_enargas.py

      - name: Subir archivos Excel descargados como Artefactos
        uses: actions/upload-artifact@v4
        with:
          name: Archivos-GNC-2026
          path: descargas_gnc/*.xls
          retention-days: 7
